// Dumps POSEIDON_COMP_CONSTS as C arrays for CUDA poseidon252.cuh
// Run: cargo run --release
use starknet_crypto_codegen::poseidon_consts;
use starknet_ff::FieldElement;
poseidon_consts!();

fn main() {
    // POSEIDON_COMP_CONSTS is generated by the macro above.
    // Layout:
    //   first 4 full rounds:  idx 0..11  (4 × 3 elements)
    //   compressed partial rounds + 1st of last full round: idx 12..97 (86 elements: 83 partial×1 + 1 full×3)
    //   last 3 full rounds:   remaining (3 × 3 = 9 elements)
    // Total: 12 + 86 + 9 = 107 elements
    //
    // poseidon_permute_comp layout:
    //   Full rounds 0..4: idx += 3 each   -> idx 0,3,6,9
    //   Partial rounds:   idx += 1 each   -> idx 12,13,...,94
    //   Full rounds 4..8: idx += 3 each   -> idx 95,98,101,104

    eprintln!("POSEIDON_COMP_CONSTS length: {}", POSEIDON_COMP_CONSTS.len());

    // Convert FieldElement to [u64; 4] little-endian
    fn to_u64x4(fe: starknet_ff::FieldElement) -> [u64; 4] {
        // Return Montgomery-form limbs so constants match GPU state representation.
        fe.into_mont()
    }

    println!("// AUTO-GENERATED -- DO NOT EDIT");
    println!("// POSEIDON_COMP_CONSTS for GPU Poseidon permutation");
    println!("// {} elements total", POSEIDON_COMP_CONSTS.len());
    println!();
    println!("#pragma once");
    println!("#include \"fp252.cuh\"");
    println!();
    println!("#define POSEIDON_FULL_ROUNDS    8");
    println!("#define POSEIDON_PARTIAL_ROUNDS 83");
    println!("#define POSEIDON_TOTAL_ROUNDS   91");
    println!("#define POSEIDON_COMP_CONSTS_LEN {}", POSEIDON_COMP_CONSTS.len());
    println!();
    println!("// Compressed round constants matching poseidon_permute_comp");
    println!("// Full round uses 3 consecutive elements; partial round uses 1 (applied to state[2])");
    print!("__constant__ Fp252 POSEIDON_COMP_CONSTS_GPU[{}] = {{", POSEIDON_COMP_CONSTS.len());

    for (i, fe) in POSEIDON_COMP_CONSTS.iter().enumerate() {
        let limbs = to_u64x4(*fe);
        if i % 3 == 0 { print!("\n    "); }
        print!("{{{{0x{:016x}ULL, 0x{:016x}ULL, 0x{:016x}ULL, 0x{:016x}ULL}}}}",
            limbs[0], limbs[1], limbs[2], limbs[3]);
        if i + 1 < POSEIDON_COMP_CONSTS.len() { print!(", "); }
    }
    println!("\n}};");

    // Print test vector for verification
    eprintln!("\nTest: poseidon_hash(0, 0)");
    let h = starknet_crypto::poseidon_hash(FieldElement::ZERO, FieldElement::ZERO);
    eprintln!("  = 0x{:x}", h);
    let h2 = starknet_crypto::poseidon_hash(
        FieldElement::from_hex_be("0x0b662f9017fa7956fd70e26129b1833e10ad000fd37b4d9f4e0ce6884b7bbe").unwrap(),
        FieldElement::from_hex_be("0x01fe356bf76102cdae1bfbdc173602ead228b12904c00dad9cf16e035468bea").unwrap(),
    );
    eprintln!("Test: poseidon_hash(0x0b662..., 0x01fe3...) = 0x{:x}", h2);
    eprintln!("Expected:                                      0x75540825a6ecc5dc7d7c2f5f868164182742227f1367d66c43ee51ec7937a81");
}
